# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zCbWjvnrJLQWWpN20GeF70lKgAqiC4wp

#제목1
##제목1
###마크다운으로 이미지와 링클 넣기
1.하나
2.둘
*이탤릭체 텍스트*
3.셋
--------------
[네이버](https://www.naver.com)

![장미](https://ssl.pstatic.net/melona/libs/1427/1427546/ad5ad63776d78e2465ce_20221222173104691.jpg)
"""



jupyter nbconvert --to markdown "/content/drive/

from tensorflow.python.client import device_lib
device_lib.list_local_devices()
import platform
platform.platform()

cat /etc/issue.net

cat /proc/meminfo

!df -h

!nvidia-smi

!python --version

!ls

"""# 새 섹션"""